default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.25.0
    hooks:
      - id: commitizen
  - repo: local
    hooks:
      - id: format
        name: format
        entry: pipenv run format
        language: system
        stages: [pre-commit]
        pass_filenames: false
      - id: lint
        name: lint
        entry: pipenv run lint
        language: system
        stages: [pre-commit]
        pass_filenames: false
      - id: test
        name: test
        entry: pipenv run test-cov
        language: system
        stages: [pre-push]
        pass_filenames: false
