[tool.ruff]
target-version = "py311"
line-length = 88

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    "W",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # mccabe
    "C90",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # flake8-annotations
    "ANN",
    # flake8-type-checking
    "TCH",
    # flake8-logging
    "LOG",
    # flake8-logging-format
    "G",
    # flake8-errmsg
    "EM",
    # flake8-implicit-str-concat
    "ISC",
    # flake8-import-conventions
    "ICN",
    # flake8-self
    "SLF",
    # flake8-unused-arguments
    "ARG",
    # flake8-return
    "RET",
    # flake8-pie
    "PIE",
    # flake8-pyi,
    "PYI",
    # flake8-quotes,
    "Q",
    # flake8-builtins
    "A",
    # flake8-commas
    "COM",
    # flake8-boolean-trap
    "FBT",
    # flake8-comprehensions
    "C4",
    # flake8-datetimez
    "DTZ",
    # flake8-bandit
    "S",
    # flake8-use-pathlib
    "PTH",
    # Pylint
    "PL",
    # Ruff-specific rules
    "RUF",
    # Perflint
    "PERF",
    # flake8-pytest-style,
    "PT",
    # isort
    "I",
]
