name: nottar-user

services:
  devcontainer:
    build:
      context: .
    volumes:
      - ../:/workspaces/nottar-user:cached
      - bash_history:/commandhistory
    network_mode: service:mongodb
    command: sleep infinity
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  bash_history:
